src/GestureManager.cpp, src/GestureManager.hpp, src/main.cpp
- feat: block touch events to apps after gestures
- fix: return correct inhibit codes in touch handlers
=> feat: Block touch events to apps after triggering a gesture

flake.lock, flake.nix, nix/default.nix
simplify nix files, use similar structure to hyprland official plugin repo
=> nix overhaul

src/gestures/Gestures.cpp, src/gestures/test/MockGestureManager.cpp
e.g. Direction for swipe from left edge can now be up/down/right instead of just right
=> feat: allow more directions for edge swipes

src/main.cpp
- fix: send cancel events instead of touch_up to clients
- fixup! fix: send cancel events instead of touch_up to clients
=> Fix: send cancel events to clients instead of touch_up

README.md
#26
Manual installation instructions will be added later
=> update README installation instructions

nix/default.nix
=> fix: gcc13 required since hyprland format rework

src/GestureManager.cpp
hyprland migrated to std::format
=> fix: log format

flake.lock, src/main.cpp
Checks for version mismatch and sends a warning notification.
TODO:
- maybe skip check for `hyprland < 0.31`?
=> Feat hl version check

.clang-format, src/GestureManager.cpp, src/GestureManager.hpp, src/gestures/Gestures.cpp, src/gestures/Gestures.hpp, src/gestures/test/MockGestureManager.cpp, src/gestures/test/MockGestureManager.hpp, src/gestures/test/test.cpp, src/main.cpp
- chore: update clang-format rules
- format: add missing 'this'
- rename for consistency
- refactor: switch to enum class for TouchGestureType
=> use more consistent style rules

README.md, src/GestureManager.cpp, src/gestures/Gestures.cpp, src/gestures/Gestures.hpp, src/gestures/test/test.cpp
see #67
adds new gesture event: `tap`
usage (see README):
```
bind = , tap:3, exec, notify-send hi
```
=> feat multi tap

README.md, scripts/hotreload, src/GestureManager.cpp, src/GestureManager.hpp, src/gestures/Gestures.cpp, src/gestures/Gestures.hpp, src/gestures/test/MockGestureManager.cpp, src/gestures/test/MockGestureManager.hpp, src/gestures/test/test.cpp, src/main.cpp
closes #67 
adds long press gesture, which can be `bindm`ed
```
bindm = ,longpress:3, movewindow
```
=> feat: long press gesture

README.md, src/GestureManager.cpp, src/GestureManager.hpp, src/gestures/Gestures.cpp, src/gestures/Gestures.hpp, src/gestures/test/test.cpp, src/main.cpp
- internal: emit edge swipe drag events
- dev: add config option workspace_swipe_edge
- feat: add workspace swipe from edge
- fixup! feat: add workspace swipe from edge
=> feat workspace edge swipe

src/GestureManager.cpp
=> Fix: drag gestures getting cancelled due to bad cancel events

src/gestures/CompletedGesture.cpp, src/gestures/CompletedGesture.hpp, src/gestures/DragGesture.cpp, src/gestures/DragGesture.hpp, src/gestures/Gestures.cpp, src/gestures/Gestures.hpp, src/gestures/Shared.cpp, src/gestures/Shared.hpp, src/gestures/meson.build, src/gestures/test/test.cpp
- internal: stop long press timer where needed
- test: allow unknown failure
- refactor: move definitions to more meaningful places
- refactor: extract small structs from main module
=> refactor: reorganize some structs

flake.lock, src/GestureManager.cpp, src/main.cpp
- chore: bump Hyprland version
- fix: migrate to hyprlang for config
=> fix: migrate to hyprlang for config

src/GestureManager.cpp
=> fix: terrible migration to hyprlang

flake.lock, src/GestureManager.cpp
=> Fix hl change

flake.lock, src/GestureManager.cpp
This is the problematic  [commit](https://github.com/hyprwm/wlroots-hyprland/commit/34219b03342b1947f0a8e6ea3aab30663523a1e0).
=> Fix type mismatch in touch gesture cancellation due to wlroot update (issue #107)

flake.lock, hyprload.toml, src/main.cpp
Callbacks need more adjustments as of: https://github.com/hyprwm/Hyprland/commit/e91513a5e8953cfbb69320d94e495ccf2d4d58f3
Tested on my end: Hyprgrass Plugin loads and works as expected with this change.
=> HyprlandAPI Breaking Change Fix

flake.lock, flake.nix, src/GestureManager.cpp, src/GestureManager.hpp, src/main.cpp
- **nix: update hyprland url**
- **nix: update flake.lock**
- **fix: hyprland API changes**
=> fix hl api break

src/GestureManager.cpp
=> fix: missing monitor offset in longpress drag

src/GestureManager.cpp, src/main.cpp
- **add `hyprgrass:debug:binds` dispatcher**
- **fix: register bindm as mouse properly**
- **reword log**
=> fix mouse binds using hyprgrass-bindm

src/GestureManager.cpp, src/GestureManager.hpp, src/gestures/Gestures.cpp
=> Workspace swipe rework

flake.lock, hyprpm.toml, src/GestureManager.cpp, src/GestureManager.hpp
- **nix: update flake to hyprland 0.41.0**
- **fix: hl-0.41.0 changes**
- **chore: update commit pin**
=> Update to hyprland v0.41.0

README.md, flake.lock, src/GestureManager.cpp, src/GestureManager.hpp, src/HyprLogger.hpp, src/gestures/Gestures.cpp, src/gestures/Gestures.hpp, src/gestures/Logger.hpp, src/gestures/Shared.hpp, src/gestures/test/CoutLogger.hpp, src/gestures/test/MockGestureManager.cpp, src/gestures/test/MockGestureManager.hpp, src/gestures/test/test.cpp, src/main.cpp
- **feat: new option edge_margin**
- **docs: add edge_margin**
=> Add option edge_margin

.github/workflows/main.yml
hopefullly ci tests are now faster
=> ci: add hyprland cachix as substituter

README.md, src/GestureManager.cpp, src/GestureManager.hpp, src/main.cpp
- **feat: resize border on long press**
- **feat: modify gaps_in to indicate resize_on_border**
- **feat: turn on border resize**
- **fix: use CCssGaps for gaps_in**
=> feature: resize with long press on window border/gaps

.github/workflows/checks.yml, docs/event_hooks.md, examples/hyprgrass-pulse/Debouncer.hpp, examples/hyprgrass-pulse/README.md, examples/hyprgrass-pulse/globals.hpp, examples/hyprgrass-pulse/main.cpp, examples/hyprgrass-pulse/meson.build, examples/hyprgrass-pulse/pulse.cpp, examples/hyprgrass-pulse/pulse.hpp, examples/meson.build, flake.nix, hyprload.toml, meson.build, meson_options.txt, nix/hyprgrass-pulse.nix, scripts/hotreload, src/GestureManager.cpp, src/GestureManager.hpp, src/main.cpp, src/meson.build
Exposes event hooks of edge gestures. Other plugins can use this hook to integrate with hyprgrass
Hyprgrass-pulse is an example plugin that let's you control audio volume with edge gestures
=> Edge hooks and hyprgrass-pulse

meson.build
=> meson: fix build failures outside nix

flake.lock, hyprpm.toml, src/GestureManager.cpp
There were only some objects changed to pointers so I fixed those.
Also added the hyprpm pin
=> Chase Hyprland changes

flake.lock, hyprpm.toml, src/GestureManager.cpp, src/GestureManager.hpp, src/VecSet.cpp
- updated flake.lock
- added missing includes
- fixed the warning about comparison of different signedness
=> Chasing Hyprland latest once again.

flake.lock, hyprpm.toml, src/TouchVisualizer.cpp
Simple change to chase https://github.com/hyprwm/Hyprland/commit/e9510115039e7ae9fcf2778e8455e7beed3424ea and also added a pin for hyprpm
=> Chase CBox changes

flake.lock, src/main.cpp
fixes build errors on hl-v0.47.2
=> migrate to addDispatcherV2

src/GestureManager.cpp
=> Swipe hooks

flake.lock, hyprpm.toml, src/GestureManager.cpp
I didn't bother to bissect which hyprland commit breaks, I just pinned hyprpm to the latest commit. I can bissect if that's important to you.
=> Chase Hyprland's changes with CConfig

examples/hyprgrass-pulse/main.cpp, flake.lock, hyprpm.toml, src/GestureManager.cpp, src/TouchVisualizer.cpp
https://github.com/hyprwm/Hyprland/commit/241a4935a244f403fa7108259075b04c81ed258f
=> Chase class members refactor

flake.lock, hyprpm.toml, src/GestureManager.cpp, src/GestureManager.hpp, src/TouchVisualizer.cpp
Here we go again.
I found this which indicates there's gonna be more refactors: https://github.com/hyprwm/Hyprland/issues/9870
I'll mark this ready for review once all the refactors are done and I've chased them all.
=> Chase Hyprland refactors Part 2

flake.lock, hyprpm.toml, src/TouchVisualizer.cpp
https://github.com/hyprwm/Hyprland/commit/a907ecd4ff736a3a09410532b405a437eb48033c
=> Chases renderTexture changes

flake.lock, hyprpm.toml, src/GestureManager.cpp
https://github.com/hyprwm/Hyprland/pull/11490
=> Chase touchpad gesture changes
