horriblename/hyprgrass

- src/GestureManager.cpp
- src/main.cpp
Add and use config values "workspace_swipe_fingers" and "sensitivity".
Also fix previous uses of internal functions to get config values; use
`HyprlandAPI::getConfigValue()` instead
- fix: initialize g_pGestureManager after adding configs
- feat: new config "sensitivity"
- feat: use config values
- cleanup old constants
- fix: use API to get config values
> feat: use config values instead of temp constants

- flake.lock
- flake.nix
- meson.build
- nix/default.nix
- nix/meson-build.patch
- src/GestureManager.cpp
- src/GestureManager.hpp
- src/globals.hpp
- src/main.cpp
Use header include path specified in the hyprland v0.25.0 update
Building nix plugins is not fully working yet, so a workaround patch to meson build file is included
- meson: set buildtype to release
- nix: update hyprland
- workaround(nix): patch meson to work on nix
- fix include statements
> Update hyprland headers to v0.25

- src/gestures/Gestures.cpp
- src/gestures/Gestures.hpp
- src/gestures/test/MockGestureManager.cpp
follow up to #17, which was prematurely merged into testing branch
This pr implements the specifics of the edge swipe events emitted
- Revert "feat: allow more directions for edge swipes (#17)"
- internal: rework find_swipe_edges
- feat!: more expressive edge swipe events
> feat! edge events in any direction

- README.md
- flake.nix
- hyprload.toml
- meson.build
- nix/default.nix
- src/GestureManager.cpp
- src/main.cpp
- src/meson.build
the old name (hyprland-touch-gestures) was long and annoying to type out, so I shortened it to touch-gestures in random places; this inconsistency caused some problems with hyprload, not to mention even _I_ can't remember where I used the full name and where I shortened it
This rename fixes issues with hyprload
(I finally touched grass)
> rename project to hyprgrass

- src/GestureManager.cpp
- src/GestureManager.hpp
- src/gestures/Gestures.cpp
- src/gestures/Gestures.hpp
- src/gestures/test/MockGestureManager.cpp
- src/gestures/test/MockGestureManager.hpp
- src/gestures/test/test.cpp
- src/main.cpp
this PR aims to reduce unwanted side effects when using gestures, by sending cancel events to client surfaces as soon as enough(3) fingers touch the screen, instead of waiting for the gesture direction to be determined
> feat: send cancel events to client surfaces earlier

- README.md
- flake.nix
- src/GestureManager.cpp
- src/main.cpp
sending cancel events sometimes causes crashes, most likely related to xwayland (#53). This PR disables cancel events by default as a temporary workaround
- fix: don't send cancel events by default, as they have caused crashes
- cleanup: remove old warning
- chore: update README on new config options
> workaround no cancel

- src/gestures/Gestures.cpp
Edge swipe was unreasonably hard to trigger, this lowers the threshold to match swipe thresholds
> fix: edge swipe lower base threshold

- README.md
The hyprland wiki is not very clear, but I think this is a better syntax. Anyway, using the previous syntax with nix home-manager lead to a silent override ([here](https://github.com/nix-community/home-manager/blob/93e804e7f8a1eb88bde6117cd5046501e66aa4bd/modules/services/window-managers/hyprland.nix#L202)).
> Update README: hyprland config example

- .gitignore
- src/GestureManager.cpp
Since the return type of `g_pCompositor->m_pLastMonitor->activeWorkspace` got changed, it no longer was able to be used with `GetWorkplaceByID` .
Removal of that surrounding function resolved issue #100 for me.
Using `g_pInputManager` is indeed probably the correct thing, but this is more of a stopgap solution.
Might be horribly wrong, who knows, tell me what you think.
> removed GetWorkplaceByID call

- src/main.cpp
Hyprland Recently changed their API and Hyprgrass callbacks need to be changed accordingly.
* Fixes building Hyprgrass against Hyprland (Git/HEAD).
> HyprLandAPI registerCallBackDynamic API change

- src/GestureManager.cpp
Gestures previously do not take monitor offset into consideration. this PR fixes that
> fix: missing monitor offset

- src/GestureManager.cpp
- src/GestureManager.hpp
- src/main.cpp
The original implementation does not do all the bookkeeping done by normal mouse events. Hopefully using the private mouseMoveUnified() will improve this
> improve compatibility with mouse binds

- README.md
- src/GestureManager.hpp
- src/main.cpp
closes #114 
- **feat: use plugin-scoped keyword for binds**
- **clear internalBinds preConfigReload**
- **add deprecation warning for touchBind**
- **rename keywords**
- **update README**
> new bind syntax: use touchbind keyword

- flake.lock
- flake.nix
- nix/default.nix
upstream no longer uses meson, we add it ourselves
> nix: re-add deps removed by upstream

- src/meson.build
Same as https://github.com/hyprwm/hyprland-plugins/pull/64 but for this plugin.
> Fix build on openSUSE.

- src/GestureManager.cpp
> fix: segfault

- src/GestureManager.cpp
- src/gestures/Actions.cpp
- src/gestures/Actions.hpp
- src/gestures/Gestures.cpp
- src/gestures/test/test.cpp
> wait for all fingers to be lifted before completing long press

- flake.lock
- flake.nix
- hyprpm.toml
- nix/default.nix
- src/GestureManager.hpp
- src/HyprLogger.hpp
- src/main.cpp
- updated `flake.lock`
- bumped gcc to 14 since that's what is used for Hyprland
- fixed the build failures due to names getting changed by https://github.com/hyprwm/Hyprland/commit/8bbeee11734d3ba8e2cf15d19cb3c302f8bfdbf2
- added pin for hyprpm
> Once again chasing latest Hyprland breaking changes

- README.md
- src/GestureManager.cpp
- src/GestureManager.hpp
- src/main.cpp
emulates touchpad swipe when swiping in a not-workspace-swipe direction. only triggered when finger count is workspace_swipe_fingers. this is to avoid interpreting every swipe as a touchpad swipe (which might not be desired)
> Emulate touchpad swipe

- flake.nix
- src/TouchVisualizer.cpp
- src/TouchVisualizer.hpp
- src/main.cpp
- src/meson.build
- **add visualize_touch config value**
- **add basic TouchVisualizer class**
- **remove unused**
- **meson: build Visualizer**
- **visualizer: try to draw something**
- **main: wire up visualizer**
- **dumb moment**
- **add render hook**
- **FINALLY DRAWS SOMETHING**
- **remove debug log**
- **fix: circle**
- **fix: hl breaking changes**
- **nix: export inputs for debugging**
- **tweak numbers**
- **fix: use monitor pixel size**
- **draw all fingers**
- **fix: renamed upstream header**
- **damage finger on touch events**
- **remove unused damageAll**
- **render texture only in ctor**
- **pre-determine pixel coords on touch events**
- **hook prerender**
- **adapt upstream breaking changes**
- **move damage out of prerender**
- **damage monitor cuz i can't be arsed anymore**
- **fix: check …
> Add circles on touch for debugging

- hyprpm.toml
- scripts/ci/pin-latest-hyprland
I ran into a gcc bug trying to build against v0.46.0 so I guess we're skipping that :/
I can't be bothered to check but if v0.46.0 is good against current main just let me know and I'll add a pin
> Chore update pin

- flake.nix
- nix/default.nix
- nix/hyprgrass-pulse.nix
Make the version of nix packages more inline with what is expected by nix tools.
For example, `nix-output-monitor`:
Before:
After:
This also allows [nvd](https://git.sr.ht/~khumba/nvd) to correctly parse version changes
> build: improve nix versioning

- flake.nix
- nix/default.nix
- nix/hyprgrass-pulse.nix
- instead of using a specific stdenv in multiple places, I just use hyprland's
- add hyprland overlays in `withPkgsFor`
- replace `gcc14Stdenv.mkDerivation` with `hyprlandPlugins.mkHyprlandPlugin`
> Nix code cleanup

- README.md
- flake.nix
- src/GestureManager.cpp
- src/gestures/Gestures.cpp
- src/gestures/Gestures.hpp
- src/gestures/test/test.cpp
Motivation: this should make hyprgrass a more "complete" solution for other plugins to use (via
event hooks)
- No longer sends cancel event to windows on three finger touch down (still sends cancel on a valid
swipe/hold/etc.)
- the arbitrary limit doesn't make much sense and might break applications that use 3-finger 
gestures.
> Allow 1 and 2-finger swipes/taps

- src/GestureManager.cpp
- src/GestureManager.hpp
- src/TouchVisualizer.cpp
- src/TouchVisualizer.hpp
- src/VecSet.hpp
- src/gestures/Actions.hpp
There was a build failure on latest Hyprland because of a specific include and I just removed it and it worked, so I figured I could remove all the unneeded includes to prevent that kind of problem from occurring.
> refactor: clean up includes

- hyprpm.toml
After reading the README.md, I've missed the option to enable hyprgrass-pulse through hyprpm. Of course it means one needs to install the pulse deps too, even if they did not plan to enable it, but hyprgrass only.
Builds sucessfuly and hyprgrass-pulse can be enabled separately
```
user@linux:~$ hyprpm enable hyprgrass-pulse
[sudo] password for attis: 
✔ Enabled hyprgrass-pulse
✔ Ensuring plugin load state
✔ Loaded hyprgrass-pulse
✔ Plugin load state ensured
user@linux:~$ hyprpm list
→ Repository hyprgrass:
│ Plugin hyprgrass
└─ enabled: true
│ Plugin hyprgrass-pulse
└─ enabled: true
→ Repository hyprland-plugins:
│ Plugin borders-plus-plus
└─ enabled: false
....
```
> Update hyprpm.toml - hypergrass-pulse added

- hyprload.toml
- hyprpm.toml
There is an issue I described in #265, introduced by the addition of the second plugin `hyprgrass-pulse` to `hyprpm.toml`, preventing the plugin from working when built via hyprpm.
Apparently, when hyprpm builds a repo with multiple plugins, it runs the build commands for both, and then copies both `.so` files wherever they need to go.
So here's a dramatic reenactment of what is happening when you add this repo via `hyprpm`:
```sh
meson setup build
ninja -C build
meson setup build -Dhyprgrass=false -Dhyprgrass-pulse=true # overwrites the build/ directory
ninja -C build
cp build/src/libhyprgrass.so /whereever/hyprpm/stores/binaries/hyprgrass.so
cp build/examples/hyprgrass-pulse/libhyprgrass-pulse.so /whereever/hyprpm/stores/binaries/hyprgrass-pulse.so
```
My proposed solution is to …
> fix: broken hyprpm build (& backport to hyprload)
